// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRfSlb3W8aoWjrLjmu1fR_YChQ2iQpOo',
    appId: '1:488190958355:web:3b035ce7dac567f17dd8e6',
    messagingSenderId: '488190958355',
    projectId: 'lumo-2f2bb',
    authDomain: 'lumo-2f2bb.firebaseapp.com',
    storageBucket: 'lumo-2f2bb.firebasestorage.app',
    measurementId: 'G-QLSGTMXJ5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSbeIj49DVqsY1Rx49NVUp51syBBsI4M',
    appId: '1:488190958355:android:8aa104a0ec67cc837dd8e6',
    messagingSenderId: '488190958355',
    projectId: 'lumo-2f2bb',
    storageBucket: 'lumo-2f2bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2Lfhme5QtBn7kbxl-7qbYn3vGxl-G4I',
    appId: '1:488190958355:ios:283aa5af9d2ad17c7dd8e6',
    messagingSenderId: '488190958355',
    projectId: 'lumo-2f2bb',
    storageBucket: 'lumo-2f2bb.firebasestorage.app',
    iosBundleId: 'com.example.lumo',
  );
}
